# Generated by Django 5.2.4 on 2025-07-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rating', models.CharField(max_length=10)),
                ('review_count', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=50)),
                ('starting_point', models.CharField(max_length=255)),
                ('distance', models.FloatField()),
                ('time_req', models.CharField(max_length=50)),
                ('locaction_url', models.URLField()),
            ],
        ),
    ]
