# Generated by Django 5.2.4 on 2025-07-14 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gscraper', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scrapedata',
            old_name='locaction_url',
            new_name='location_url',
        ),
    ]
